web1:
    build: ./one
    ports:
      - "5001:5000"
    volumes:
      - ./one:/code
    links:
      - redis
web2:
    build: ./two
    ports:
      - "5002:5000"
    volumes:
      - ./two:/code
    links:
      - redis

redis:
    image: redis
