# Version: 0.0.1
FROM ubuntu:14.04
MAINTAINER Arialdo Martini "arialdomartini@gmail.com"

RUN apt-get install -y nginx
RUN echo "This is a static website running inside a docker container" > /usr/share/nginx/html/index.html

EXPOSE 80